import type { Lesson, LessonModule } from '@/types/tutorial';

export const LESSONS: Lesson[] = [
  // --- BEGINNER ---
  {
    id: 'board-setup',
    title: 'The Chess Board',
    description: 'Learn how the board is set up and how pieces are arranged.',
    category: 'beginner',
    difficulty: 1,
    xpReward: 50,
    estimatedMinutes: 5,
    icon: '♟',
    tags: ['basics', 'setup'],
    objectives: ['Understand the 8x8 board', 'Know the starting positions', 'Understand ranks, files, and diagonals'],
    steps: [
      {
        id: 'board-intro',
        type: 'explanation',
        title: 'Welcome to Chess',
        description: 'Chess is played on an 8×8 board with 64 squares. The board has alternating light and dark squares. Each player starts with 16 pieces.',
        fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
        highlightSquares: ['a1', 'h8'],
      },
      {
        id: 'board-coordinates',
        type: 'explanation',
        title: 'Ranks and Files',
        description: 'Columns are called "files" (a–h) and rows are called "ranks" (1–8). Each square has a unique name like "e4" or "d5".',
        fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
        highlightSquares: ['e4', 'd5', 'a1', 'h8'],
      },
      {
        id: 'board-setup-check',
        type: 'quiz',
        title: 'Quick Check',
        description: 'Which square does the white king start on?',
        quizOptions: [
          { id: 'a', text: 'd1', isCorrect: false, explanation: 'd1 is where the white queen starts.' },
          { id: 'b', text: 'e1', isCorrect: true, explanation: 'Correct! The white king always starts on e1.' },
          { id: 'c', text: 'e8', isCorrect: false, explanation: 'e8 is where the black king starts.' },
          { id: 'd', text: 'f1', isCorrect: false, explanation: 'f1 is where the white bishop starts.' },
        ],
        correctAnswer: 'b',
      },
    ],
  },
  {
    id: 'pawn-moves',
    title: 'The Pawn',
    description: 'Learn how pawns move, capture, and their special moves.',
    category: 'beginner',
    difficulty: 1,
    xpReward: 75,
    estimatedMinutes: 8,
    icon: '♙',
    tags: ['pieces', 'pawns'],
    objectives: ['Understand pawn movement', 'Learn pawn captures', 'Understand the initial two-square move'],
    steps: [
      {
        id: 'pawn-forward',
        type: 'explanation',
        title: 'How Pawns Move',
        description: 'Pawns move forward one square at a time. On their first move, they can advance two squares. Pawns capture diagonally, one square forward.',
        fen: '4k3/8/8/8/8/8/4P3/4K3 w - - 0 1',
        highlightSquares: ['e3', 'e4'],
        arrows: [{ from: 'e2', to: 'e3', color: '#22c55e' }, { from: 'e2', to: 'e4', color: '#3b82f6' }],
      },
      {
        id: 'pawn-move-practice',
        type: 'move',
        title: 'Move the Pawn',
        description: 'Move the pawn forward two squares from its starting position.',
        fen: '4k3/8/8/8/8/8/4P3/4K3 w - - 0 1',
        expectedMove: 'e4',
        highlightSquares: ['e2', 'e4'],
        hints: ['Click on the pawn on e2, then click on e4', 'The pawn can move to e3 or e4 from its starting square'],
        explanation: 'Pawns on their starting square can leap forward two squares!',
      },
      {
        id: 'pawn-capture',
        type: 'explanation',
        title: 'Pawn Captures',
        description: 'Pawns capture diagonally — one square forward and to the side. This means a pawn on e4 can capture on d5 or f5.',
        fen: '4k3/8/8/3p1p2/4P3/8/8/4K3 w - - 0 1',
        highlightSquares: ['d5', 'f5'],
        arrows: [{ from: 'e4', to: 'd5', color: '#ef4444' }, { from: 'e4', to: 'f5', color: '#ef4444' }],
      },
      {
        id: 'pawn-capture-practice',
        type: 'move',
        title: 'Capture the Pawn',
        description: 'Capture the black pawn on d5.',
        fen: '4k3/8/8/3p4/4P3/8/8/4K3 w - - 0 1',
        expectedMove: 'exd5',
        highlightSquares: ['e4', 'd5'],
        hints: ['Click e4, then click d5 to capture', 'Pawns capture diagonally forward'],
        explanation: 'You captured the pawn! When a pawn takes another pawn, we call it "exd5" - the e-pawn takes on d5.',
      },
    ],
  },
  {
    id: 'knight-moves',
    title: 'The Knight',
    description: 'Learn the unique L-shaped movement of the knight.',
    category: 'beginner',
    difficulty: 1,
    xpReward: 75,
    estimatedMinutes: 7,
    icon: '♞',
    tags: ['pieces', 'knight'],
    objectives: ['Understand the L-shaped move', 'Know that knights can jump over pieces'],
    steps: [
      {
        id: 'knight-intro',
        type: 'explanation',
        title: 'The Knight Moves in an L',
        description: 'The knight is the only piece that can jump over other pieces! It moves in an L-shape: two squares in one direction, then one square perpendicular (or vice versa).',
        fen: '7k/8/8/8/4N3/8/8/7K w - - 0 1',
        highlightSquares: ['d6', 'f6', 'c5', 'g5', 'c3', 'g3', 'd2', 'f2'],
        arrows: [
          { from: 'e4', to: 'd6', color: '#a855f7' },
          { from: 'e4', to: 'f6', color: '#a855f7' },
          { from: 'e4', to: 'c5', color: '#a855f7' },
          { from: 'e4', to: 'g5', color: '#a855f7' },
        ],
      },
      {
        id: 'knight-move-practice',
        type: 'move',
        title: 'Move the Knight',
        description: 'Move the knight to f6 — the standard knight development square.',
        fen: '7k/8/8/8/4N3/8/8/7K w - - 0 1',
        expectedMove: 'Nf6',
        highlightSquares: ['e4', 'f6'],
        hints: ['Click the knight on e4', 'Then click f6 (2 up, 1 right from e4)'],
        explanation: 'Knights are often developed toward the center where they control many squares.',
      },
    ],
  },
  {
    id: 'bishop-moves',
    title: 'The Bishop',
    description: 'Master the diagonal movement of the bishop.',
    category: 'beginner',
    difficulty: 1,
    xpReward: 75,
    estimatedMinutes: 7,
    icon: '♝',
    tags: ['pieces', 'bishop'],
    objectives: ['Understand diagonal movement', 'Know that bishops stay on one color'],
    steps: [
      {
        id: 'bishop-intro',
        type: 'explanation',
        title: 'Bishops Move Diagonally',
        description: 'Bishops move any number of squares diagonally. Each player has two bishops — one on light squares and one on dark squares. A bishop can never change the color of its square!',
        fen: '7k/8/8/8/3B4/8/8/7K w - - 0 1',
        highlightSquares: ['e5', 'f6', 'g7', 'h8', 'c5', 'b6', 'a7', 'e3', 'f2', 'g1', 'c3', 'b2', 'a1'],
        arrows: [
          { from: 'd4', to: 'h8', color: '#f59e0b' },
          { from: 'd4', to: 'a1', color: '#f59e0b' },
        ],
      },
    ],
  },
  {
    id: 'rook-moves',
    title: 'The Rook',
    description: 'Learn how the powerful rook moves along ranks and files.',
    category: 'beginner',
    difficulty: 1,
    xpReward: 75,
    estimatedMinutes: 6,
    icon: '♜',
    tags: ['pieces', 'rook'],
    objectives: ['Understand straight-line movement', 'Know rook value and power'],
    steps: [
      {
        id: 'rook-intro',
        type: 'explanation',
        title: 'Rooks Rule the Open Files',
        description: 'Rooks move any number of squares horizontally or vertically. They are powerful pieces, especially on open files (columns with no pawns).',
        fen: '7k/8/8/8/4R3/8/8/7K w - - 0 1',
        highlightSquares: ['e1', 'e2', 'e3', 'e5', 'e6', 'e7', 'e8', 'a4', 'b4', 'c4', 'd4', 'f4', 'g4', 'h4'],
        arrows: [
          { from: 'e4', to: 'e8', color: '#06b6d4' },
          { from: 'e4', to: 'a4', color: '#06b6d4' },
        ],
      },
    ],
  },
  {
    id: 'queen-moves',
    title: 'The Queen',
    description: 'Learn why the queen is the most powerful piece on the board.',
    category: 'beginner',
    difficulty: 1,
    xpReward: 100,
    estimatedMinutes: 8,
    icon: '♛',
    tags: ['pieces', 'queen'],
    objectives: ['Understand queen movement', 'Know the queen\'s value'],
    steps: [
      {
        id: 'queen-intro',
        type: 'explanation',
        title: 'The Queen is the Most Powerful',
        description: 'The queen combines the power of the rook and bishop — it can move any number of squares in any direction: horizontally, vertically, or diagonally.',
        fen: '7k/8/8/8/3Q4/8/8/7K w - - 0 1',
        highlightSquares: ['d1', 'd2', 'd3', 'd5', 'd6', 'd7', 'd8', 'a4', 'b4', 'c4', 'e4', 'f4', 'g4', 'h4', 'a1', 'b2', 'c3', 'e5', 'f6', 'g7', 'h8', 'a7', 'b6', 'c5', 'e3', 'f2', 'g1'],
      },
    ],
  },
  {
    id: 'king-moves',
    title: 'The King',
    description: 'Learn how the king moves and why it must be protected.',
    category: 'beginner',
    difficulty: 1,
    xpReward: 100,
    estimatedMinutes: 8,
    icon: '♚',
    tags: ['pieces', 'king'],
    objectives: ['Understand king movement', 'Understand check and checkmate'],
    steps: [
      {
        id: 'king-intro',
        type: 'explanation',
        title: 'Protect Your King at All Costs',
        description: 'The king moves one square in any direction. The king is the most important piece — if your king is captured (checkmate), you lose. Never leave your king in danger!',
        fen: '7k/8/8/8/3K4/8/8/8 w - - 0 1',
        highlightSquares: ['c3', 'd3', 'e3', 'c4', 'e4', 'c5', 'd5', 'e5'],
      },
      {
        id: 'king-move-practice',
        type: 'move',
        title: 'Move the King to Safety',
        description: 'Move the king to e4.',
        fen: '7k/8/8/8/3K4/8/8/8 w - - 0 1',
        expectedMove: 'Ke4',
        highlightSquares: ['d4', 'e4'],
        hints: ['Click the king on d4', 'Then click e4'],
        explanation: 'Good! The king moved one square to the right.',
      },
    ],
  },
  {
    id: 'check-basics',
    title: 'Check & Checkmate',
    description: 'Learn what check and checkmate are and how to respond.',
    category: 'beginner',
    difficulty: 2,
    xpReward: 150,
    estimatedMinutes: 12,
    icon: '⚠️',
    tags: ['check', 'checkmate', 'basics'],
    objectives: ['Understand check', 'Know the 3 ways to escape check', 'Understand checkmate'],
    steps: [
      {
        id: 'check-intro',
        type: 'explanation',
        title: 'What is Check?',
        description: 'Your king is "in check" when it is under attack by an opponent\'s piece. You MUST respond to check immediately. You have three options: move the king, block the attack, or capture the attacking piece.',
        fen: '7k/8/8/8/8/8/4r3/4K3 w - - 0 1',
        highlightSquares: ['e1', 'e2'],
        arrows: [{ from: 'e2', to: 'e1', color: '#ef4444' }],
      },
      {
        id: 'escape-check',
        type: 'move',
        title: 'Escape from Check',
        description: 'Your king is in check! Move it to a safe square.',
        fen: '7k/8/8/8/8/8/4r3/4K3 w - - 0 1',
        expectedMove: 'd1',
        highlightSquares: ['e1', 'd1', 'f1'],
        hints: ['Move the king away from the e-file', 'The king can go to d1 or f1'],
        explanation: 'You escaped check by moving the king off the e-file. The rook can no longer attack it.',
      },
      {
        id: 'checkmate-intro',
        type: 'explanation',
        title: 'What is Checkmate?',
        description: 'Checkmate is when the king is in check AND there is no legal move to escape. The game is over! The player who delivers checkmate wins.',
        fen: '6k1/5ppp/8/8/8/8/8/6RK w - - 0 1',
        highlightSquares: ['g8'],
        arrows: [{ from: 'g1', to: 'g8', color: '#ef4444' }],
      },
    ],
  },
  {
    id: 'castling',
    title: 'Castling',
    description: 'Learn the special castling move to protect your king.',
    category: 'beginner',
    difficulty: 2,
    xpReward: 125,
    estimatedMinutes: 10,
    icon: '🏰',
    tags: ['special-moves', 'castling', 'king-safety'],
    objectives: ['Understand kingside and queenside castling', 'Know the conditions for castling'],
    steps: [
      {
        id: 'castling-intro',
        type: 'explanation',
        title: 'Castling: King Safety Move',
        description: 'Castling is a special move involving the king and a rook. The king moves two squares toward a rook, and the rook jumps to the other side of the king. This tucks your king away safely!',
        fen: 'r3k2r/pppppppp/8/8/8/8/PPPPPPPP/R3K2R w KQkq - 0 1',
        highlightSquares: ['e1', 'g1', 'h1'],
        arrows: [{ from: 'e1', to: 'g1', color: '#22c55e' }, { from: 'h1', to: 'f1', color: '#3b82f6' }],
      },
      {
        id: 'castling-conditions',
        type: 'explanation',
        title: 'When Can You Castle?',
        description: 'You can castle if: (1) The king has not moved. (2) The rook has not moved. (3) No pieces between king and rook. (4) King is not in check. (5) King does not pass through or land on an attacked square.',
        fen: 'r3k2r/pppppppp/8/8/8/8/PPPPPPPP/R3K2R w KQkq - 0 1',
        highlightSquares: ['f1', 'g1'],
      },
      {
        id: 'castling-practice',
        type: 'move',
        title: 'Castle Kingside',
        description: 'Castle kingside — move the king to g1.',
        fen: 'r3k2r/pppppppp/8/8/8/8/PPPPPPPP/R3K2R w KQkq - 0 1',
        expectedMove: 'O-O',
        highlightSquares: ['e1', 'g1'],
        hints: ['Click the king on e1, then click on g1 to castle', 'Castling moves the king two squares toward the rook'],
        explanation: 'Excellent! You castled kingside. The king moved to g1 and the rook jumped to f1.',
      },
    ],
  },
  {
    id: 'en-passant',
    title: 'En Passant',
    description: 'Learn the special pawn capture called en passant.',
    category: 'beginner',
    difficulty: 3,
    xpReward: 150,
    estimatedMinutes: 10,
    icon: '⚡',
    tags: ['special-moves', 'en-passant', 'pawns'],
    objectives: ['Understand when en passant is possible', 'Execute the en passant capture'],
    steps: [
      {
        id: 'ep-intro',
        type: 'explanation',
        title: 'En Passant: The Ghost Capture',
        description: '"En passant" is French for "in passing." It happens when a pawn uses its initial two-square advance to land beside an enemy pawn. The enemy can capture it AS IF it had only moved one square — but only immediately!',
        fen: '7k/8/8/3pP3/8/8/8/7K w - d6 0 1',
        highlightSquares: ['e5', 'd5', 'd6'],
        arrows: [{ from: 'e5', to: 'd6', color: '#f59e0b' }],
      },
      {
        id: 'ep-practice',
        type: 'move',
        title: 'Capture En Passant',
        description: 'The black pawn just moved from d7 to d5. Capture it en passant!',
        fen: '7k/8/8/3pP3/8/8/8/7K w - d6 0 1',
        expectedMove: 'exd6',
        highlightSquares: ['e5', 'd6'],
        hints: ['Move your pawn diagonally to d6', 'The captured pawn disappears from d5'],
        explanation: 'Perfect en passant capture! The black pawn on d5 is removed even though you moved to d6.',
      },
    ],
  },
  {
    id: 'promotion',
    title: 'Pawn Promotion',
    description: 'Learn how to promote a pawn and why it\'s powerful.',
    category: 'beginner',
    difficulty: 2,
    xpReward: 125,
    estimatedMinutes: 8,
    icon: '👑',
    tags: ['special-moves', 'promotion', 'pawns'],
    objectives: ['Understand pawn promotion', 'Know what to promote to and when'],
    steps: [
      {
        id: 'promo-intro',
        type: 'explanation',
        title: 'Promote Your Pawn!',
        description: 'When a pawn reaches the opposite end of the board (8th rank for white, 1st rank for black), it can be promoted to a queen, rook, bishop, or knight. Almost always promote to a queen!',
        fen: '7k/4P3/8/8/8/8/8/7K w - - 0 1',
        highlightSquares: ['e7', 'e8'],
        arrows: [{ from: 'e7', to: 'e8', color: '#f59e0b' }],
      },
    ],
  },

  // --- INTERMEDIATE ---
  {
    id: 'forks',
    title: 'Forks',
    description: 'Learn to attack two pieces at once with a fork.',
    category: 'intermediate',
    difficulty: 3,
    xpReward: 200,
    estimatedMinutes: 15,
    icon: '⚔️',
    tags: ['tactics', 'forks'],
    objectives: ['Recognize fork opportunities', 'Execute knight forks', 'Execute pawn forks'],
    prerequisites: ['knight-moves', 'check-basics'],
    steps: [
      {
        id: 'fork-intro',
        type: 'explanation',
        title: 'The Fork Tactic',
        description: 'A fork is when one piece attacks two (or more) enemy pieces at the same time. The opponent can only save one, so you win material. Knights are especially good at forking because of their unusual movement.',
        fen: '8/8/8/3k4/8/4N3/8/3K4 w - - 0 1',
        highlightSquares: ['d5', 'f7', 'c4'],
        arrows: [{ from: 'e3', to: 'c4', color: '#a855f7' }],
      },
      {
        id: 'fork-practice',
        type: 'move',
        title: 'Find the Fork',
        description: 'Find a knight move that forks the black king and rook.',
        fen: '8/5r2/8/3k4/8/4N3/8/3K4 w - - 0 1',
        expectedMove: 'Nc4',
        highlightSquares: ['e3', 'c4'],
        hints: ['Look for a square where the knight attacks both the king and rook', 'Knights move in L-shapes — try c4'],
        explanation: 'Brilliant! Nc4 forks the king on d5 and the rook on f7. The king must move, and you win the rook!',
      },
    ],
  },
  {
    id: 'pins',
    title: 'Pins',
    description: 'Learn how to pin enemy pieces so they can\'t move.',
    category: 'intermediate',
    difficulty: 3,
    xpReward: 200,
    estimatedMinutes: 12,
    icon: '📌',
    tags: ['tactics', 'pins'],
    objectives: ['Identify absolute and relative pins', 'Use pins to win material'],
    prerequisites: ['bishop-moves', 'rook-moves', 'queen-moves'],
    steps: [
      {
        id: 'pin-intro',
        type: 'explanation',
        title: 'What is a Pin?',
        description: 'A pin occurs when a piece is attacked and cannot move without exposing a more valuable piece behind it. An absolute pin is when the piece behind is the king — the pinned piece literally cannot move legally!',
        fen: '7k/4r3/8/8/4B3/8/4K3/8 w - - 0 1',
        highlightSquares: ['e4', 'e7', 'e2'],
        arrows: [{ from: 'e4', to: 'e7', color: '#f59e0b' }],
      },
    ],
  },
  {
    id: 'skewers',
    title: 'Skewers',
    description: 'The reverse pin — attack a valuable piece to win what\'s behind it.',
    category: 'intermediate',
    difficulty: 3,
    xpReward: 200,
    estimatedMinutes: 12,
    icon: '🗡️',
    tags: ['tactics', 'skewers'],
    objectives: ['Understand the skewer tactic', 'Execute skewers to win material'],
    prerequisites: ['pins'],
    steps: [
      {
        id: 'skewer-intro',
        type: 'explanation',
        title: 'The Skewer: Reverse Pin',
        description: 'A skewer is like a pin in reverse. Instead of a less valuable piece being attacked in front, the MORE valuable piece is attacked first. When it moves, you capture the piece behind it.',
        fen: '8/4k3/8/8/8/8/4R3/4K3 w - - 0 1',
        highlightSquares: ['e2', 'e7'],
        arrows: [{ from: 'e2', to: 'e7', color: '#06b6d4' }],
      },
    ],
  },
  {
    id: 'discovered-attacks',
    title: 'Discovered Attacks',
    description: 'Unleash a hidden attack by moving a piece out of the way.',
    category: 'intermediate',
    difficulty: 4,
    xpReward: 250,
    estimatedMinutes: 15,
    icon: '💥',
    tags: ['tactics', 'discovered-attacks'],
    objectives: ['Recognize discovered attack opportunities', 'Execute double attacks'],
    prerequisites: ['pins', 'forks'],
    steps: [
      {
        id: 'disc-intro',
        type: 'explanation',
        title: 'The Discovered Attack',
        description: 'A discovered attack happens when you move one piece, revealing an attack by another piece behind it. The piece you moved can also make a threat, creating a double threat that\'s very hard to stop!',
        fen: '8/4r3/8/4k3/8/4B3/8/4R2K w - - 0 1',
        highlightSquares: ['e3', 'e7', 'e1'],
        arrows: [
          { from: 'e3', to: 'f4', color: '#a855f7' },
          { from: 'e1', to: 'e7', color: '#ef4444' },
        ],
      },
    ],
  },
  {
    id: 'openings-intro',
    title: 'Chess Openings',
    description: 'Learn the principles behind good opening play.',
    category: 'intermediate',
    difficulty: 3,
    xpReward: 200,
    estimatedMinutes: 20,
    icon: '🎯',
    tags: ['openings', 'strategy'],
    objectives: ['Learn the 3 opening principles', 'Understand center control', 'Develop pieces efficiently'],
    prerequisites: ['castling'],
    steps: [
      {
        id: 'opening-principles',
        type: 'explanation',
        title: '3 Opening Principles',
        description: 'The 3 golden rules of opening play: (1) Control the center with pawns or pieces. (2) Develop your pieces (knights before bishops). (3) Castle early to keep your king safe.',
        fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
        highlightSquares: ['d4', 'e4', 'd5', 'e5'],
      },
      {
        id: 'e4-open',
        type: 'move',
        title: 'Control the Center',
        description: 'Start with 1.e4 — the most popular first move, controlling the center.',
        fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
        expectedMove: 'e4',
        highlightSquares: ['e2', 'e4'],
        hints: ['Move the e-pawn forward two squares', 'Click e2, then e4'],
        explanation: '1.e4! Excellent. This controls the center and opens lines for the queen and bishop.',
      },
    ],
  },

  // --- ADVANCED ---
  {
    id: 'endgame-basics',
    title: 'King & Pawn Endgames',
    description: 'Master the fundamental endgame of king and pawns.',
    category: 'advanced',
    difficulty: 4,
    xpReward: 300,
    estimatedMinutes: 25,
    icon: '♟',
    tags: ['endgame', 'king', 'pawns'],
    objectives: ['Activate the king in endgames', 'Understand the opposition', 'Convert pawn advantages'],
    prerequisites: ['pawn-moves', 'king-moves', 'promotion'],
    steps: [
      {
        id: 'endgame-king-active',
        type: 'explanation',
        title: 'Activate Your King in Endgames',
        description: 'Unlike the middlegame, in endgames the king becomes a powerful piece! You should centralize your king and use it actively. A centralized king controls more squares and supports pawn promotion.',
        fen: '8/8/8/4k3/8/8/4P3/4K3 w - - 0 1',
        highlightSquares: ['e1', 'd2', 'e2', 'f2'],
        arrows: [{ from: 'e1', to: 'e2', color: '#22c55e' }],
      },
      {
        id: 'opposition-intro',
        type: 'explanation',
        title: 'The Opposition',
        description: 'Two kings are "in opposition" when they stand on the same rank or file with one square between them, and it\'s your opponent\'s turn to move. Gaining the opposition forces the enemy king back.',
        fen: '8/8/8/4k3/8/4K3/8/8 w - - 0 1',
        highlightSquares: ['e3', 'e5'],
      },
    ],
  },
  {
    id: 'sacrifice-tactics',
    title: 'Sacrifices & Combinations',
    description: 'Learn to give up material for a decisive advantage.',
    category: 'advanced',
    difficulty: 5,
    xpReward: 400,
    estimatedMinutes: 30,
    icon: '💎',
    tags: ['tactics', 'sacrifices', 'calculation'],
    objectives: ['Recognize sacrifice opportunities', 'Calculate forcing sequences', 'Evaluate material vs positional compensation'],
    prerequisites: ['forks', 'pins', 'discovered-attacks'],
    steps: [
      {
        id: 'sacrifice-intro',
        type: 'explanation',
        title: 'When to Sacrifice Material',
        description: 'A sacrifice is giving up material (pieces or pawns) to gain a non-material advantage like: open lines to the king, a mating attack, piece activity, or positional dominance.',
        fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 4 4',
        highlightSquares: ['f7'],
        arrows: [{ from: 'c4', to: 'f7', color: '#ef4444' }],
      },
    ],
  },
];

export const LESSON_MODULES: LessonModule[] = [
  {
    id: 'beginner-basics',
    title: 'Chess Basics',
    description: 'Learn the fundamentals — piece movement, rules, and basic strategy.',
    category: 'beginner',
    icon: '♟',
    isUnlocked: true,
    lessons: LESSONS.filter((l) => l.category === 'beginner'),
  },
  {
    id: 'intermediate-tactics',
    title: 'Tactics & Strategy',
    description: 'Master tactical patterns and build a strategic foundation.',
    category: 'intermediate',
    icon: '⚔️',
    isUnlocked: false,
    lessons: LESSONS.filter((l) => l.category === 'intermediate'),
  },
  {
    id: 'advanced-mastery',
    title: 'Advanced Mastery',
    description: 'Elevate your game with advanced concepts and calculation.',
    category: 'advanced',
    icon: '👑',
    isUnlocked: false,
    lessons: LESSONS.filter((l) => l.category === 'advanced'),
  },
];

export function getLessonById(id: string): Lesson | undefined {
  return LESSONS.find((l) => l.id === id);
}
